image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_REPO: "sudarsan935"
  IMAGE_NAME: "demo"
  TAG: "3.0"
    
stages:
  - build
  - docker_build

build_job:
  image: maven-3-jdk-8
  stage: build
  script:
    - mvn package
  artifact:
    paths:
      - Dockerfile
      - target/*.jar
      
docker_build_job:
  stage: docker_build
  script:
    - docker build -t $DOCKER_REPO/$IMAGE_NAME:$TAG .
    - docker login -u sudarsan935 -p $docker_pwd
    - docker push $DOCKER_REPO/$IMAGE_NAME:$TAG
